CREATE TABLE ALTERTEST (COL1 INTEGER);

ALTER TABLE ALTERTEST RENAME TO ALTERDEMO;

ALTER TABLE ALTERDEMO RENAME COLUMN COL1 TO DEMOCOL;

ALTER TABLE ALTERDEMO ADD COLUMN COL2 INTEGER;

ALTER TABLE ALTERDEMO ALTER COLUMN COL2 SET DEFAULT 0;

ALTER TABLE ALTERDEMO ALTER COLUMN COL2 DROP DEFAULT;

CREATE TABLE PERMTEST (COL INTEGER);

-- GRANT SELECT ON PERMTEST TO ANOTHER;

GRANT ALL ON PERMTEST TO PUBLIC;

