--CREATE TABLE CUSTOMER(
--	CUSTOMER_ID INTEGER PRIMARY KEY,
--	CNAME		CHAR(30),
--	TELEPHONE 	CHAR(20),
--	STREET		CHAR(30),
--	CITY		CHAR(30),
--	STATE		CHAR(2),
--	ZIPCODE		CHAR(10),
--	COUNTRY		CHAR(20)
--);

-- TABLE WITH FOREIGN KEY ACTIONS
CREATE TABLE CUSTOMER (
	CUSTOMER_ID	INTEGER,
	NAME		CHAR(30),
	TELEPHONE	CHAR(20),
	STREET		CHAR(40),
	CITY		CHAR(30),
	STATE		CHAR(2) REFERENCES STATENAME
				ON UPDATE CASCADE
				ON DELETE SET NULL,
	ZIPCODE		CHAR(10),
	COUNTRY		CHAR(20)
);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID 	INTEGER PRIMARY KEY,
	NAME		CHAR(30),
	HIRE_DATE	DATE
);

CREATE TABLE PART(
	PART_ID		INTEGER PRIMARY KEY,
	ENAME		CHAR(30),
	COST		NUMERIC(8,2),
	WEIGHT		FLOAT
);

CREATE TABLE SALESORDER(
	ORDER_ID	INTEGER,
	CUSTOMER_ID	INTEGER REFERENCES CUSTOMER,
	EMPLOYEE_ID 	INTEGER REFERENCES EMPLOYEE,
	PART_ID		INTEGER	REFERENCES PART,
	ORDER_DATE	DATE,
	SHIP_DATE	DATE,
	PAYMENT		NUMERIC(8,2)
);

