CREATE TABLE COPYTEST(
	INTCOL 	INTEGER,
	NUMCL	NUMERIC(16,2),
	TEXTCOL	TEXT,
	BOOLCOL	BOOLEAN
);

INSERT INTO COPYTEST VALUES (1, 23.99, 'FRESH SPRINT WATER', 'T');
INSERT INTO COPYTEST VALUES (2, 55.23, 'BOTTLED SODA', 'T');

SELECT * FROM COPYTEST;

COPY COPYTEST TO '/tmp/copytest.csv' USING DELIMITERS ',';

DELETE FROM COPYTEST;

COPY COPYTEST FROM '/tmp/copytest.csv' USING DELIMITERS ',';
