BEGIN WORK;
	DECLARE CUSTOMER_CURSOR CURSOR FOR
	SELECT CUSTOMER_ID FROM CUSTOMER;

	FETCH 1 FROM CUSTOMER_CURSOR;

	FETCH 2 FROM CUSTOMER_CURSOR;

	FETCH -1 FROM CUSTOMER_CURSOR;

	FETCH -2 FROM CUSTOMER_CURSOR;

	MOVE 10 FROM CUSTOMER_CURSOR;

	FETCH 1 FROM CUSTOMER_CURSOR;

	CLOSE CUSTOMER_CURSOR;

COMMIT WORK;
