CREATE TABLE REALTABLE (COL INTEGER);

CREATE VIEW VIEW_REALTABLE AS SELECT * FROM REALTABLE;

INSERT INTO REALTABLE VALUES (1);

INSERT INTO VIEW_REALTABLE VALUES (2);

SELECT * FROM REALTABLE;

SELECT * FROM VIEW_REALTABLE;

CREATE RULE VIEW_REALTABLE_INSERT AS
ON INSERT TO VIEW_REALTABLE
DO INSTEAD
	INSERT INTO REALTABLE
	VALUES (NEW.COL);

CREATE RULE VIEW_REALTABLE_UPDATE AS
ON UPDATE TO VIEW_REALTABLE
DO INSTEAD
	UPDATE REALTABLE
	SET COL = NEW.COL
	WHERE COL = OLD.COL;

CREATE RULE VIEW_REALTABLE_DELETE AS
ON DELETE TO VIEW_REALTABLE
DO INSTEAD
	DELETE FROM REALTABLE
	WHERE COL = OLD.COL;

