CREATE TABLE PARENT_TEST(COL1 INTEGER);

CREATE TABLE CHILD_TEST (COL2 INTEGER) INHERITS (PARENT_TEST);

\d PARENT_TEST

\d CHILD_TEST

INSERT INTO PARENT_TEST VALUES (1);
INSERT INTO CHILD_TEST VALUES (2,3);

SELECT * FROM PARENT_TEST;

SELECT * FROM CHILD_TEST;

SELECT * FROM PARENT_TEST*;

CREATE TABLE GRANDCHILD_TEST (COL3 INTEGER) INHERITS (CHILD_TEST);

\d GRANDCHILD_TEST

INSERT INTO GRANDCHILD_TEST VALUES (4,5,6);

SELECT * FROM PARENT_TEST*;

SELECT * FROM CHILD_TEST*;
