SELECT 	F1.FIRSTNAME, F1.LASTNAME, F1.AGE
FROM 	FRIEND F1, FRIEND F2
WHERE	F1.STATE = F2.STATE
GROUP BY F1.STATE, F1.FIRSTNAME, F1.LASTNAME, F1.AGE 
HAVING 	F1.AGE = MAX(F2.AGE)
ORDER	BY FIRSTNAME, LASTNAME;

SELECT 	F1.FIRSTNAME, F1.LASTNAME, F1.AGE
FROM	FRIEND F1
WHERE	AGE = (
		SELECT MAX(F2.AGE)
		FROM FRIEND F2
		WHERE F1.STATE = F2.STATE
	)
ORDER BY FIRSTNAME, LASTNAME;
