SELECT FILM.TITLE, CONCAT(ACTOR.FIRST_NAME, ' ', ACTOR.LAST_NAME) AS ACTOR
FROM FILM, FILM_ACTOR, ACTOR
WHERE FILM.FILM_ID = FILM_ACTOR.FILM_ID AND
      FILM_ACTOR.ACTOR_ID = ACTOR.ID
ORDER BY FILM.TITLE;
