SELECT F1.FIRSTNAME, F1.LASTNAME, F1.STATE
FROM FRIEND F1, FRIEND F2
WHERE 	F1.STATE<> F2.STATE AND
	F2.FIRSTNAME = 'DICK' AND
	F2.LASTNAME = 'GLEASON'
ORDER BY FIRSTNAME, LASTNAME;

SELECT F1.FIRSTNAME, F1.LASTNAME, F1.STATE
FROM FRIEND F1
WHERE F1.STATE <> (
			SELECT F2.STATE
			FROM FRIEND F2
			WHERE 	F2.FIRSTNAME = 'DICK' AND
				F2.LASTNAME = 'GLEASON'
		  )
ORDER BY FIRSTNAME, LASTNAME;

