SELECT 	FIRST_NAME
FROM	EMPLOYEES
WHERE	EMPLOYEE_ID NOT IN (
				SELECT EMPLOYEE_ID
				FROM EMPLOYEES
			);

SELECT 	FIRST_NAME
FROM 	EMPLOYEES
WHERE	EMPLOYEE_ID <> ALL (
				SELECT EMPLOYEE_ID
				FROM EMPLOYEES
			);

SELECT 	FIRST_NAME
FROM	EMPLOYEES
WHERE	NOT EXISTS (
			SELECT EMPLOYEE_ID
			FROM EMPLOYEES
		);
