-- EMPLOYEES WHO WORKS UNDER MANAGER_ID = 100
SELECT DISTINCT	FIRST_NAME
FROM	EMPLOYEES
WHERE	EMPLOYEE_ID IN (
			SELECT EMPLOYEE_ID
			FROM EMPLOYEES
			WHERE MANAGER_ID = 100
		);
-- EMPLOYEES WHO WORK NOT UNDER MANAGER_ID  = 100
SELECT DISTINCT FIRST_NAME
FROM 	EMPLOYEES
WHERE	EMPLOYEE_ID NOT IN(
				SELECT EMPLOYEE_ID
				FROM EMPLOYEES
				WHERE MANAGER_ID = 100
			);

